export const ServiceCategories = {
    nanny: 'Nanny',
    chef:'Chef',
    privateCoach: 'Private Coach',
    chaufeur: 'Chaufeur',
    maid: 'Maid',
    gardener: 'Gardener',
    instructor: 'Instructor',
    worker: 'Worker',
    shepherd: 'Shepherd', 
    privatePro:'Private PRO',
    privateSailor:'Private Sailor',
    falconTrainer:'Falcon Trainer',
    nurse:'Nurse',
    groomer: 'Groomer',
    houseKeeper: 'House Keeper',
    labourer:'Labourer',
    farmer:'Farmer',
    agricultureEng: 'Agriculture Eng.',
    watchMan:'Watch Man',
    privateTutor: 'Pivate Tutor'
}