export const Colors = {
    tabGrdientTop: '#DBDBDB',
    tabGradientBottom: '#F7F7F7',
    mainColor: '#463795',
    homeScreenBottomGradient: '#66439F',
    listScreenTopGradient:'#D9A0AF',
    searchBackgroundColor:'#F0BBD2',
    whiteOpacity05:'rgba(255,255,255,0.5)',
    drawerColor:'#1F0D7B',
    drawerOpacity:'rgba(31,13,123,0.5)',

    nanny:'#F89A9A',
    chefColor:'#FDD485',
    privateCoach:'#C29AF8',
    chaufeur:'#6285FA',
    maid:'#D9A0AF',
    gardener:'#79D097',
    worker:'#FFEAEA',
    shepherd:'#AAAAAA',
    privatePro:'#99D3CE',
    privateSailor:'#75A2EA',
    falconTrainer:'#E9F7F8',
    nurse:'#90B1E5',
    groomer:'#F7C2A1',
    houseKeeper:'#FFEEBF',
    lobourer:'#FCFFAA',
    farmer:"#E4FCD5",
    agricultureEng:'#CBFFE3',
    watchMan:'#E7C3F7',
    privateTutor:'#A5E3E8',
    searchNanny:'#FFC7C7',
    searchChef:'#F3D59C',
    searchPrivateCoach:'#D9BEFF',
    searchChaufeur:'#9FB5FF',
    searchMaid:'#F0BBD2',
    searchGardener:'#9AE5B4',
    searchWorker:'#CBB8D2',
    searchShepherd:'#C6C4CD',
    searchPrivatePro:"#D2EFEC",
    searchPrivateSailor:'#6884D2',
    searchFalconTrainer:'#B6BBD9',
    searchNurse:"#A6C1ED",
    searchGroomer:'#FDDDC9',
    searchHouseKeeper:'#C7B7B2',
    searchLobourer:'#D6D6A5',
    searchFarmer:'#BECCC5',
    searchAgricultureEng:'#A4C4CC',
    searchWatchMan:'#BD9EDD',
    searchPrivateTutor:'#85AACC'
}